### ISSUE TITLE
is possible put compatibility with .net 6+ and Angular 15 - Clean?

### ISSUE THREAD

**Issue by johnfelipe** [MJeorrett/CleanGenerator#26]

**Comment by MJeorrett** [comment]
Hey @johnfelipe it should be very straightforward to downgrade the generated code from 7 to 6 by changing the Sdk in the .csproj files and maybe dongrading some of the nuget packages.  However I would question why you are not wanting to use the latest version for a new project.  Re Angluar, the tool does not currently scaffold front end code.  Plans are in the pipeline but they are a long way off TBH.
