### ISSUE TITLE
pls share a video with deployment test use

### ISSUE THREAD

**Issue by johnfelipe** [MJeorrett/CleanGenerator#28]
pls share a video with deployment test use

**Comment by MJeorrett** [comment]
Hey @johnfelipe I'm not sure exactly what you mean.  Are you asking for a video of how to use the tool or something else?  The README should cover how to get started with the project.  Once you have installed it you can run `cleangen --help` to see how to use the tool.

**Comment by johnfelipe** [comment]
Yes how to use in a case use

**Comment by johnfelipe** [comment]
Help me with a little video for how use tool in real life...

**Comment by johnfelipe** [comment]
> Hey @johnfelipe I'm not sure exactly what you mean. Are you asking for a video of how to use the tool or something else? The README should cover how to get started with the project. Once you have installed it you can run `cleangen --help` to see how to use the tool.

YES video of how to use the tool pls
