### ISSUE TITLE
Mark files as created by CleanGen

### ISSUE THREAD

**Issue by jonotassia** [MJeorrett/CleanGenerator#50]
It would be useful to have some mechanism to mark files as created by CleanGen. This is particularly valuable during PR reviews, as CleanGen can create quite a bit of noise

**Comment by MJeorrett** [comment]
I’m not sure I agree. Cleangen is a scaffolding tool so any code it generates should be modified / removed if it is “noise”.

**Comment by jonotassia** [comment]
Yeah, I think I misunderstood the original slack messages that prompted this from Simon. I'll close this one, as I agree with you. Just because code is auto-generated, doesn't mean it shouldn't be considered in a review.

**Comment by jonotassia** [comment]
Closing
