### ISSUE TITLE
Create output folder if it doesn't exist

### ISSUE THREAD

**Issue by MickMelon** [MJeorrett/CleanGenerator#6]
Currently, when you specify an output folder that doesn't exist, the program will fail. 

```
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\workspace\CleanGenerator\tesdfgdgdft-output'.
```

The output folder should be created if it does not already exist.

**Comment by MJeorrett** [comment]
Just bumped in to this again. Seems like it would be a really quick win and I think not doing this is a bit unexpected.
